name: gen_protect
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - langdetect
  - tqdm
  - openai=0.28.1
  - pytorch
  - regex
  - xgboost
  - mypy
  - prompt_toolkit
  - pyyaml
  - pydantic
  - python-levenshtein
  - tiktoken
  - transformers
  - seaborn
  - selenium
  - xmltodict
  - tokenizers>=0.13.3
  - spacy
  - compilers
  - pip:
      - presidio-analyzer==2.2.33
      - presidio-anonymizer==2.2.33
      - google-cloud-aiplatform
      - selenium-stealth
      - folktables
      - pyinputplus
      - accelerate
      - sentence-transformers
      - gradio
      - duckdb
      - azure-ai-textanalytics
      - together
      - anthropic
      - ollama
