output_dir: "results"
seed: 10
task: "ANONYMIZED"
dryrun: False
save_prompts: True
timeout: 0.0
task_config: 
    run_eval_inference: true
    profile_path: "anonymized_results/synthetic/gpt1_test/inference_2.jsonl"
    outpath: "anonymized_results/synthetic/gpt1_test"
    anonymizer: 
      anon_type: "llm"
      target_mode: "single"
      max_workers: 4
    eval_inference_model:
      name: "gpt-4.1"
      provider: "openai"
      args: {
        temperature: 0.1
      }
    anon_model:
      name: "gpt-4.1"
      provider: "openai"
      args: {
        temperature: 0.1
      }
    inference_model:
      name: "gpt-4.1"
      provider: "openai"
      args: {
        temperature: 0.1
      }
    utility_model:
      name: "gpt-4.1"
      provider: "openai"
      args: {
        temperature: 0.1
      }
    profile_filter:
      hardness: 1
      certainty: 1
      num_tokens: 1000
    max_num_iterations: 2
    use_ner: False
    offset: 0
    num_profiles: 1
gen_model:
  name: "gpt-4.1"
  provider: "openai"
  args: {
    temperature: 0.1
  }
