output_dir: "results"
seed: 10
task: "ANONYMIZED"
dryrun: False
save_prompts: True
timeout: 0.0
task_config: 
    profile_path: "data/synthetic/synthetic_dataset.jsonl"
    outpath: "anonymized_results/synthetic/azure_full"
    anonymizer: 
      anon_type: "azure"
      target_mode: "single"
      max_workers: 4
    anon_model:
      name: "gpt-4"
      provider: "openai"
      args: {
        temperature: 0.1
      }
    inference_model:
      name: "gpt-4"
      provider: "openai"
      args: {
        temperature: 0.1
      }
    utility_model:
      name: "gpt-4"
      provider: "openai"
      args: {
        temperature: 0.1
      }
    profile_filter:
      hardness: 1
      certainty: 1
      min_num_tokens: 500
      num_tokens: 1000
    max_num_iterations: 1
    use_ner: False
    offset: 0
    num_profiles: 1000
gen_model:
  name: "gpt-4"
  provider: "openai"
  args: {
    temperature: 0.1
  }
