output_dir: "results"
seed: 10
task: "ANONYMIZED"
dryrun: False
save_prompts: True
timeout: 0.0
task_config: 
    profile_path: "anonymized_results/gpt4_turbo_full/inference_0.jsonl"
    outpath: "anonymized_results/gpt35_turbo_base"
    anonymizer: 
      anon_type: "llm_base"
      target_mode: "single"
      max_workers: 8
    anon_model:
      name: "gpt-3.5-turbo-16k-0613"
      provider: "openai"
      args: {
        temperature: 0.1
      }
    inference_model:
      name: "gpt-3.5-turbo-16k-0613"
      provider: "openai"
      args: {
        temperature: 0.1
      }
    utility_model:
      name: "gpt-4-1106-preview"
      provider: "openai"
      args: {
        temperature: 0.1
      }
    # eval_inference_model:
    #   name: "gpt-4"
    #   provider: "openai"
    #   args: {
    #     temperature: 0.1
    #   }
    profile_filter:
      hardness: 1
      certainty: 1
      num_tokens: 1000
    max_num_iterations: 5
    use_ner: False
    offset: 0
    num_profiles: 1000
gen_model:
  name: "gpt-3.5-turbo-16k-0613"
  provider: "openai"
  args: {
    temperature: 0.1
  }
