output_dir: "results"
seed: 10
task: "ANONYMIZED"
dryrun: False
save_prompts: True
timeout: 0.0
task_config: 
    profile_path: "eval_results/full_eval.jsonl"
    outpath: "anonymized_results/gpt4_1_full"
    anonymizer: 
      anon_type: "llm"
      target_mode: "single"
      max_workers: 4
    anon_model:
      name: "gpt-4.1"
      provider: "openai"
      args: {
        temperature: 0.1
      }
    inference_model:
      name: "gpt-4.1"
      provider: "openai"
      args: {
        temperature: 0.1
      }
    utility_model:
      name: "gpt-4.1"
      provider: "openai"
      args: {
        temperature: 0.1
      }
    profile_filter:
      hardness: 1
      certainty: 1
      num_tokens: 1000
    max_num_iterations: 5
    use_ner: False
    offset: 0
    num_profiles: 1
gen_model:
  name: "gpt-4.1"
  provider: "openai"
  args: {
    temperature: 0.1
  }
