output_dir: "results"
seed: 10
task: "ANONYMIZED"
dryrun: False
save_prompts: True
timeout: 0.0
task_config: 
    run_utility_scoring: true
    profile_path: "anonymized_results/gpt35_turbo_base/eval_inference_results.jsonl"
    outpath: "anonymized_results/gpt35_turbo_base"
    anonymizer: 
      anon_type: "azure"
      target_mode: "single"
      max_workers: 4
    utility_model:
      name: "gpt-4-1106-preview"
      provider: "openai"
      args: {
        temperature: 0.1
      }
    utility_model:
      name: "gpt-4-1106-preview"
      provider: "openai"
      args: {
        temperature: 0.1
      }
    utility_model:
      name: "gpt-4-1106-preview"
      provider: "openai"
      args: {
        temperature: 0.1
      }
    profile_filter:
      hardness: 1
      certainty: 1
      num_tokens: 5000
    max_num_iterations: 1
    use_ner: False
    offset: 0
    num_profiles: 1000
gen_model:
  name: "gpt-4"
  provider: "openai"
  args: {
    temperature: 0.1
  }
